-- ENTITIES
create table products (
  id bigint generated by default as identity primary key,
  name text,
  manufacture text,
  style text,
  purchase_price money,
  sale_price money,
  quantity_on_hand int8,
  commission_percentage float4
);

create table sales_person (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  email text,
  address text,
  phone numeric,
  start_date date,
  termination_date date,
  manager text
);

create table customer (
  id bigint generated by default as identity primary key,
  first_name text,
  last_name text,
  email text,
  address text,
  phone numeric,
  start_date date
);

create table sales (
  id bigint generated by default as identity primary key,
  product text,
  sales_person text,
  customer text,
  sales_date date
);

create table discount (
  id bigint generated by default as identity primary key,
  product text,
  begin_date date,
  end_date date,
  discount_percentage float4
);